<a href="https://colab.research.google.com/github/Batorejro/Machine-Learning-boot/blob/main/missing_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Missing values

In [1]:
!pip install scikit-learn


In [3]:
!pip install --upgrade scikit-learn


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 20.2 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2


In [10]:
import numpy as np
import pandas as pd
import sklearn

sklearn.__version__


'1.4.0'

Generacja danych

In [51]:
data = {
    'size':['XL', 'L', 'M', np.nan, 'L', 'M', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red', 'green', 'white'],
    'gender': ['female', 'male', np.nan, 'male', 'female', 'female', np.nan],
    'price': [199.0, 89.0, np.nan, 99.0, 129.0, 79.0, np.nan],
    'weight':[500, 450, 300, np.nan, 410, np.nan, 380],
    'bought': ['yes', 'no', 'yes', 'no', 'yes', 'no', np.nan]
    }

df_raw = pd.DataFrame(data=data)
df_raw

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
3  NaN  green    male   99.0     NaN     no
4    L    red  female  129.0   410.0    yes
5    M  green  female   79.0     NaN     no
6    M  white     NaN    NaN   380.0    NaN

kopia

In [33]:
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   7 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      float64
 5   bought  6 non-null      object 
dtypes: float64(2), object(4)
memory usage: 464.0+ bytes


Kontrola lack_off pokazuje gdzie jest brak danych (True)

In [34]:
df.isnull()

size  color  gender  price  weight  bought
0  False  False   False  False   False   False
1  False  False   False  False   False   False
2  False  False    True   True   False   False
3   True  False   False  False    True   False
4  False  False   False  False   False   False
5  False  False   False  False    True   False
6   True  False    True   True   False    True

In [35]:
df.isnull().sum()

size      2
color     0
gender    2
price     2
weight    2
bought    1
dtype: int64

In [36]:
df.isnull().sum().sum()

9

In [37]:
df.isnull().sum() /len(df)

size      0.285714
color     0.000000
gender    0.285714
price     0.285714
weight    0.285714
bought    0.142857
dtype: float64

Klasa simpleimputer - uzupełnia dane

In [38]:
df[['weight']]

weight
0   500.0
1   450.0
2   300.0
3     NaN
4   410.0
5     NaN
6   380.0

In [40]:
from sklearn.impute import SimpleImputer
# strategy: 'mean', 'median', 'most_frequent', 'constant'
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(df[['price']])



SimpleImputer()

In [41]:
imputer.statistics_

array([119.])

In [43]:
imputer.transform(df[['price']])

array([[199.],
       [ 89.],
       [119.],
       [ 99.],
       [129.],
       [ 79.],
       [119.]])

In [48]:
df['price'] = imputer.transform(df[['price']])
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN  119.0   300.0    yes
3  NaN  green    male   99.0     NaN     no
4    L    red  female  129.0   410.0    yes
5    M  green  female   79.0     NaN     no
6  NaN  white     NaN  119.0   380.0    NaN

fit_transform - podstawianie danych

In [50]:
imputer = SimpleImputer(missing_values=np.nan, strategy='constant', fill_value=402.0)
imputer.fit_transform(df[['weight']])


array([[500.],
       [450.],
       [300.],
       [402.],
       [410.],
       [402.],
       [380.]])

In [54]:
imputer = SimpleImputer(missing_values=np.nan, strategy='constant', fill_value='L')
imputer.fit_transform(df[['size']])

array([['XL'],
       ['L'],
       ['M'],
       ['L'],
       ['L'],
       ['M'],
       ['L']], dtype=object)

In [55]:
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer.fit_transform(df[['size']])

array([['XL'],
       ['L'],
       ['M'],
       ['L'],
       ['L'],
       ['M'],
       ['L']], dtype=object)

In [58]:
df = df_raw.copy()
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
3  NaN  green    male   99.0     NaN     no
4    L    red  female  129.0   410.0    yes
5    M  green  female   79.0     NaN     no
6    M  white     NaN    NaN   380.0    NaN

from matplotlib import pyplot as plt
df['price'].plot(kind='hist', bins=20, title='price')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['weight'].plot(kind='hist', bins=20, title='weight')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('size').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('color').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('gender').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('bought').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x='price', y='weight', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['price'].plot(kind='line', figsize=(8, 4), title='price')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df['weight'].plot(kind='line', figsize=(8, 4), title='weight')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['color'].value_counts()
    for x_label, grp in df.groupby('size')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('size')
_ = plt.ylabel('color')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['gender'].value_counts()
    for x_label, grp in df.groupby('color')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('color')
_ = plt.ylabel('gender')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['bought'].value_counts()
    for x_label, grp in df.groupby('gender')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('gender')
_ = plt.ylabel('bought')

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['size'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='price', y='size', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['color'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='price', y='color', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['gender'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='price', y='gender', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['bought'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='price', y='bought', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [59]:
df.isnull().sum()

size      1
color     0
gender    2
price     2
weight    2
bought    1
dtype: int64